# Generated by Django 3.2.10 on 2022-02-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Note Deleted'),
        ),
    ]
