# Generated by Django 3.2.10 on 2022-02-14 10:45

import Apps.Profile.models
import Apps.Profile.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20220210_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='user/User.png', storage=Apps.Profile.storages.LocalStorage(), upload_to=Apps.Profile.models.user_directory_path, verbose_name='Profile Picture'),
        ),
    ]
