# Generated by Django 3.2.10 on 2022-02-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Info', '0002_feedback_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Is Feedback Deleted'),
        ),
    ]
